# Principal Component Analisys

In [1]:
import numpy as np

In [3]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
# calculate the mean
M = np.mean(A.T, axis=1)
print(M)

[3. 4.]


In [6]:
# centring the columns
C = A - M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [8]:
# calculate the covariance 
V = np.cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [9]:
# eigenvector decomposision of covariance matrix
values, vectors = np.linalg.eig(V)
print(values)
print(vectors)

[8. 0.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [11]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
